### ISSUE TITLE
Cannot be imported

### ISSUE THREAD

**Issue by CurryAyam** [ejirocodes/vue3-otp-input#3] opened 2022-02-19 11:54 UTC
got the following error
` App •  ERROR  •  UI  in ./src/pages/Index.vue?vue&type=script&lang=js

Module not found: Can't resolve imported dependency "vue3-otp-input"
Did you forget to install it? You can run: yarn add vue3-otp-input

 App •  COMPILATION FAILED  • Please check the log above for details.`

**Comment by ejirocodes** [comment] 2022-02-19 12:06
Duplicate of #2

**Closed** 2022-02-19 12:13 UTC

**Comment by CurryAyam** [comment] 2022-02-19 12:45
I’m not using typescript!Though I follow the instruction still cannot load the module  Sent from Mail for Windows From: Ejiro AsiuwhuSent: Saturday, 19 February 2022 7:06 pmTo: ejirocodes/vue3-otp-inputCc: CurryAyam; AuthorSubject: Re: [ejirocodes/vue3-otp-input] Cannot be imported (Issue #3) Duplicate of #2—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
